insert into phuong values 
(1, "Phường Cái Khế", 1),
(2, "Phường An Hòa", 1),
(3, "Phường Thới Bình", 1),
(4, "Phường An Nghiệp", 1),
(5, "Phường An Cư", 1),
(6, "Phường Tân An", 1),
(7, "Phường An Phú", 1),
(8, "Phường Xuân Khánh", 1),
(9, "Phường Hưng Lợi", 1),
(10, "Phường An Khánh", 1),
(11, "Phường An Bình", 1),
(12, "Phường Châu Văn Liêm", 2),
(13, "Phường Thới Hòa", 2),
(14, "Phường Thới Long", 2),
(15, "Phường Long Hưng", 2),
(16, "Phường Thới An", 2),
(17, "Phường Phước Thới", 2),
(18, "Phường Trường Lạc", 2),
(19, "Phường Bình Thủy", 3),
(20, "Phường Trà An", 3),
(21, "Phường Trà Nóc", 3),
(22, "Phường Thới An Đông", 3),
(23, "Phường An Thới", 3),
(24, "Phường Bùi Hữu Nghĩa", 3),
(25, "Phường Long Hòa", 3),
(26, "Phường Long Tuyền", 3),
(27, "Phường Lê Bình", 4),
(28, "Phường Hưng Phú", 4),
(29, "Phường Hưng Thạnh", 4),
(30, "Phường Ba Láng", 4),
(31, "Phường Thường Thạnh", 4),
(32, "Phường Phú Thứ", 4),
(33, "Phường Tân Phú", 4),
(34, "Phường Thốt Nốt", 5),
(35, "Phường Thới Thuận", 5),
(36, "Phường Thuận An", 5),
(37, "Phường Tân Lộc", 5),
(38, "Phường Trung Nhứt", 5),
(39, "Phường Thạnh Hoà", 5),
(40, "Phường Trung Kiên", 5),
(41, "Phường Tân Hưng", 5),
(42, "Phường Thuận Hưng", 5),
(43, "Xã Vĩnh Bình", 6),
(44, "Thị trấn Thanh An", 6),
(45, "Thị trấn Vĩnh Thạnh", 6),
(46, "Xã Thạnh Mỹ", 6),
(47, "Xã Vĩnh Trinh", 6),
(48, "Xã Thạnh An", 6),
(49, "Xã Thạnh Tiến", 6),
(50, "Xã Thạnh Thắng", 6),
(51, "Xã Thạnh Lợi", 6),
(52, "Xã Thạnh Qưới", 6),
(53, "Xã Thạnh Lộc", 6),
(54, "Xã Trung An", 7),
(55, "Xã Trung Thạnh", 7),
(56, "Xã Thạnh Phú", 7),
(57, "Xã Trung Hưng", 7),
(58, "Thị trấn Cờ Đỏ", 7),
(59, "Xã Thới Hưng", 7),
(60, "Xã Đông Hiệp", 7),
(61, "Xã Đông Thắng", 7),
(62, "Xã Thới Đông", 7),
(63, "Xã Thới Xuân", 7),
(64, "Thị trấn Phong Điền", 8),
(65, "Xã Nhơn Ái", 8),
(66, "Xã Giai Xuân", 8),
(67, "Xã Tân Thới", 8),
(68, "Xã Trường Long", 8),
(69, "Xã Mỹ Khánh", 8),
(70, "Xã Nhơn Nghĩa", 8),
(71, "Thị trấn Thới Lai", 9),
(72, "Xã Thới Thạnh", 9),
(73, "Xã Tân Thạnh", 9),
(74, "Xã Xuân Thắng", 9),
(75, "Xã Đông Bình", 9),
(76, "Xã Đông Thuận", 9),
(77, "Xã Thới Tân", 9),
(78, "Xã Trường Thắng", 9),
(79, "Xã Định Môn", 9),
(80, "Xã Trường Thành", 9),
(81, "Xã Trường Xuân", 9),
(82, "Xã Trường Xuân A", 9),
(83, "Xã Trường Xuân B", 9);

insert into huyen values
(1, "Quận Ninh Kiều"),
(2, "Quận Ô Môn"),
(3, "Quận Bình Thuỷ"),
(4, "Quận Cái Răng"),
(5, "Quận Thốt Nốt"),
(6, "Huyện Vĩnh Thạnh"),
(7, "Huyện Cờ Đỏ"),
(8, "Huyện Phong Điền"),
(9, "Huyện Thới Lai");

insert into theloai values
(1, 'Tiểu thuyết'),
(2, 'Kỹ năng sống'),
(3, 'Kinh tế'),
(4, 'Truyện thơ')
;

INSERT INTO tacgia 
VALUES 
(1, 'Marguerite Duras'), 
(2, 'Nguyễn Ngọc Tư'), 
(3, 'Nguyễn Minh Châu'), 
(4, 'Thanh Thảo'), 
(5, 'Nguyễn Nhật Ánh'), 
(6, 'Tô Hoài'), 
(7, 'Dale Carnegie'), 
(8, 'Adam Khoo'), 
(9, 'Stephen R. Covey'), 
(10, 'Nguyễn Ngọc Thạch'), 
(11, 'Brian Tracy'), 
(12, 'Jim Rohn'), 
(13, 'Tony Gaskins'), 
(14, 'Anthony Robbins'), 
(15, 'Roy F. Baumeister'), 
(16, 'PGS.TS. Đinh Trọng Thịnh'), 
(17, 'PGS.TS. Nguyễn Văn Ngọc'), 
(18, 'PGS.TS. Nguyễn Mạnh Tùng'), 
(19, 'PGS.TS. Nguyễn Đình Cẩn'),
(20, 'Nguyễn Đình Thi'),
(21, 'Bảo Ninh'),
(22, 'Đoàn Giỏi'),
(23, 'Michael J. Gelb'),
(24, 'George S. Clason'),
(25, 'Thanh Thúy');

INSERT INTO nxb
VALUES 
(1, 'Alpha Books'), 
(2, 'First News'),
(3, 'NXB Dân Trí'), 
(4, 'NXB Kim Đồng'), 
(5, 'NXB Trẻ'), 
(6, 'NXB Văn học'), 
(7, 'NXB Đại học Kinh tế Quốc dân'), 
(8, 'NXB Tài chính'),
(9, 'NXB Hội Nhà văn');

insert into sach (tensach,matacgia,manxb,maloai,mota) values
('Người tình', 1, 6, 1,10, 'Câu chuyện tình yêu giữa một cô gái trẻ Việt Nam và một chàng trai Pháp trong bối cảnh chiến tranh Việt Nam.'),
('Cánh đồng bất tận', 2, 5, 1,10, 'Câu chuyện về cuộc sống của những người dân nghèo ở miền Tây sông nước.'),
('Điều giản dị', 5, 4, 1,10, 'Câu chuyện về tình cảm gia đình và những bài học cuộc sống.'),
('Những đứa con của Rồng', 25, 5, 1,10, 'Câu chuyện về cuộc sống của những người con của Việt Nam trong thời kỳ chiến tranh.'),
('Bến quê', 3, 9, 1,10, 'Câu chuyện về một người nông dân nghèo và những giá trị giản dị của cuộc sống.'),
('Đất nước đứng lên', 20, 9, 4,10, 'Bản hùng ca về cuộc Cách mạng tháng Tám năm 1945 của nhân dân Việt Nam.'),
('Vợ chồng A Phủ', 6, 4, 1,10, 'Câu chuyện về cuộc sống và số phận của người dân miền núi Tây Bắc.'),
('Nỗi buồn chiến tranh', 21, 5, 1,10, 'Câu chuyện về những ký ức đau thương của người lính trong chiến tranh.'),
('Đất rừng phương Nam', 22, 4, 1,10,'Câu chuyện về cuộc phiêu lưu của một nhóm người trong thời kỳ kháng chiến chống Pháp.'),
('Mùa hè năm ấy', 4, 9, 1,10, 'Câu chuyện về tình yêu, tuổi trẻ và hoài niệm.'),
('Mảnh đất lắm người nhiều ma', 5, 4, 1,10, 'Câu chuyện về những câu chuyện ma và những tình cảm trong sáng của tuổi thơ.'),
('Kính vạn hoa', 5, 4, 1,10, 'Câu chuyện về một nhóm bạn thân ở tuổi học trò.'),
('Tuổi 20 – Những năm tháng quyết định cuộc đời', 10, 1, 2,10, 'Cuốn sách được chia thành ba phần: công việc, tình yêu, trí não và cơ thể. Trong từng phần, bạn sẽ được trải nghiệm các tình huống cụ thể, những cách thức suy nghĩ của những con người trong độ tuổi 20.'),
('Học cách học', 8, 1, 2,10, 'Cuốn sách cung cấp cho bạn những phương pháp học tập hiệu quả, giúp bạn học nhanh hơn, nhớ lâu hơn và đạt được mục tiêu học tập của mình.'),
('7 thói quen của người thành đạt', 9, 1, 2,10, 'Cuốn sách đề cập đến 7 thói quen quan trọng giúp bạn đạt được thành công trong cuộc sống, bao gồm: thói quen chủ động, thói quen bắt đầu trước khi có động lực, thói quen kết thúc, thói quen hợp tác, thói quen thấu hiểu người khác, thói quen tư duy thắng lợi, và thói quen tinh thần tập trung.'),
('Đắc nhân tâm', 7, 1, 2,10, 'Cuốn sách cung cấp cho bạn những kỹ năng giao tiếp hiệu quả, giúp bạn xây dựng các mối quan hệ tốt đẹp và thành công trong cuộc sống.'),
('Quẳng gánh lo đi và vui sống', 7, 1, 2,10, 'Cuốn sách giúp bạn giải tỏa căng thẳng, lo âu và sống vui vẻ, hạnh phúc hơn.'),
('Ngừng than vãn, bắt đầu hành động', 11, 2, 2,10, 'Cuốn sách giúp bạn thay đổi suy nghĩ và hành động tích cực hơn, từ đó đạt được mục tiêu của mình.'),
('Bí mật của người thành công', 12, 2, 2,10, 'Cuốn sách cung cấp cho bạn những bài học quý giá từ những người thành công, giúp bạn đạt được thành công trong cuộc sống.'),
('Đánh thức con hổ trong bạn', 14, 2, 2,10, 'Cuốn sách giúp bạn khai phá tiềm năng của bản thân và đạt được những điều phi thường.'),
('Đừng bao giờ từ bỏ ước mơ', 13, 2, 2,10, 'Cuốn sách truyền cảm hứng cho bạn theo đuổi ước mơ của mình và không bao giờ từ bỏ.'),
('Sức mạnh của ý chí', 15, 2, 2,10, 'Cuốn sách giúp bạn hiểu rõ về ý chí và cách rèn luyện ý chí để đạt được mục tiêu của mình.'),
('Hạnh phúc của một người bình thường', 5, 3, 2,10, 'Cuốn sách kể về hành trình tìm kiếm hạnh phúc của một người bình thường trong cuộc sống.'),
('Đời là những chuyến đi', 5, 3, 2,10, 'Cuốn sách kể về những chuyến đi và trải nghiệm của một người trong cuộc sống.'),
('Người giàu có nhất thành Babylon', 24, 3, 2,10, 'Cuốn sách cung cấp cho bạn những nguyên tắc làm giàu của người Babylon, giúp bạn đạt được sự giàu có và thịnh vượng.'),
('Bí quyết thành công của người Do Thái', 23, 3, 2,10, 'Cuốn sách tiết lộ những bí quyết thành công của người Do Thái, giúp bạn đạt được thành công trong cuộc sống.'),
('Quản trị tài chính doanh nghiệp', 16, 8, 3,10, 'Cuốn sách cung cấp các kiến thức cơ bản và nâng cao về quản trị tài chính doanh nghiệp, bao gồm các nội dung như: kế hoạch tài chính, phân tích tài chính, dự báo tài chính, quản lý vốn lưu động, quản lý vốn đầu tư, quản lý tài sản cố định, quản lý tài chính kế hoạch, quản lý tài chính quốc tế.'),
('Kinh tế học vĩ mô', 17, 7, 3,10, 'Cuốn sách cung cấp các kiến thức cơ bản về kinh tế vĩ mô, bao gồm các nội dung như: GDP, lạm phát, thất nghiệp, cán cân thanh toán, chính sách kinh tế vĩ mô, tăng trưởng kinh tế.'),
('Kinh tế học vi mô', 17, 7, 3,10, 'Cuốn sách cung cấp các kiến thức cơ bản về kinh tế vi mô, bao gồm các nội dung như: thị trường cạnh tranh hoàn hảo, thị trường độc quyền, thị trường cạnh tranh không hoàn hảo, chính sách kinh tế vi mô.'),
('Quản trị kinh doanh', 18, 7, 3,10,'Cuốn sách cung cấp các kiến thức cơ bản về quản trị kinh doanh, bao gồm các nội dung như: quản trị chiến lược, quản trị marketing, quản trị sản xuất, quản trị nhân lực, quản trị tài chính.'),
('Tư duy chiến lược', 18, 7, 3,10, 'Cuốn sách cung cấp các kiến thức về tư duy chiến lược, bao gồm các nội dung như: tầm nhìn, sứ mệnh, mục tiêu, chiến lược, kế hoạch, tổ chức, thực thi, kiểm tra và điều chỉnh.'),
('Quản trị Marketing', 19, 7, 3,10, 'Cuốn sách cung cấp các kiến thức cơ bản về quản trị marketing, bao gồm các nội dung như: nghiên cứu thị trường, phân tích thị trường, sản phẩm, giá cả, phân phối, xúc tiến bán.'),
('Quản trị sản xuất', 18, 7, 3,10, 'Cuốn sách cung cấp các kiến thức cơ bản về quản trị sản xuất, bao gồm các nội dung như: thiết kế sản phẩm, quy trình sản xuất, tổ chức sản xuất, kiểm soát chất lượng, quản lý dự án.'),
('Quản trị nhân lực', 18, 7, 3,10, 'Cuốn sách cung cấp các kiến thức cơ bản về quản trị nhân lực, bao gồm các nội dung như: tuyển dụng, đào tạo, phát triển, lương thưởng, đánh giá, sa thải.');