# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\CTU\DBMS\project\mainwindow\change_password.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_change_pass_page(object):
    def setupUi(self, change_pass_page):
        change_pass_page.setObjectName("change_pass_page")
        change_pass_page.resize(599, 379)
        self.gridLayout_4 = QtWidgets.QGridLayout(change_pass_page)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem, 5, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem2, 3, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem3, 1, 2, 1, 1)
        self.lineEdit_oldPass = QtWidgets.QLineEdit(change_pass_page)
        self.lineEdit_oldPass.setMinimumSize(QtCore.QSize(300, 0))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEdit_oldPass.setFont(font)
        self.lineEdit_oldPass.setStyleSheet("border: 2px  solid rgb(80, 96, 107);\n"
"border-radius: 5px;\n"
"padding: 5px;")
        self.lineEdit_oldPass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_oldPass.setObjectName("lineEdit_oldPass")
        self.gridLayout.addWidget(self.lineEdit_oldPass, 0, 2, 1, 1)
        self.label_newPass = QtWidgets.QLabel(change_pass_page)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_newPass.setFont(font)
        self.label_newPass.setObjectName("label_newPass")
        self.gridLayout.addWidget(self.label_newPass, 2, 0, 1, 1)
        self.label_oldPass = QtWidgets.QLabel(change_pass_page)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_oldPass.setFont(font)
        self.label_oldPass.setObjectName("label_oldPass")
        self.gridLayout.addWidget(self.label_oldPass, 0, 0, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.changePass_Btn = QtWidgets.QPushButton(change_pass_page)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.changePass_Btn.setFont(font)
        self.changePass_Btn.setStyleSheet("background-color: rgb(26, 116, 227);\n"
"color: rgb(255,255,255);\n"
"border-radius: 5px;\n"
"padding: 10px;")
        self.changePass_Btn.setObjectName("changePass_Btn")
        self.gridLayout_5.addWidget(self.changePass_Btn, 0, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem4, 0, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem5, 0, 2, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_5, 6, 0, 1, 3)
        self.label_confirmPass = QtWidgets.QLabel(change_pass_page)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_confirmPass.setFont(font)
        self.label_confirmPass.setObjectName("label_confirmPass")
        self.gridLayout.addWidget(self.label_confirmPass, 4, 0, 1, 1)
        self.lineEdit_newPass = QtWidgets.QLineEdit(change_pass_page)
        self.lineEdit_newPass.setMinimumSize(QtCore.QSize(300, 0))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEdit_newPass.setFont(font)
        self.lineEdit_newPass.setStyleSheet("border: 2px  solid rgb(80, 96, 107);\n"
"border-radius: 5px;\n"
"padding: 5px;")
        self.lineEdit_newPass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_newPass.setObjectName("lineEdit_newPass")
        self.gridLayout.addWidget(self.lineEdit_newPass, 2, 2, 1, 1)
        self.lineEdit_confirmPass = QtWidgets.QLineEdit(change_pass_page)
        self.lineEdit_confirmPass.setMinimumSize(QtCore.QSize(300, 0))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEdit_confirmPass.setFont(font)
        self.lineEdit_confirmPass.setStyleSheet("border: 2px  solid rgb(80, 96, 107);\n"
"border-radius: 5px;\n"
"padding: 5px;")
        self.lineEdit_confirmPass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_confirmPass.setObjectName("lineEdit_confirmPass")
        self.gridLayout.addWidget(self.lineEdit_confirmPass, 4, 2, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 0, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem6, 0, 2, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem7, 0, 0, 1, 1)

        self.retranslateUi(change_pass_page)
        QtCore.QMetaObject.connectSlotsByName(change_pass_page)

    def retranslateUi(self, change_pass_page):
        _translate = QtCore.QCoreApplication.translate
        change_pass_page.setWindowTitle(_translate("change_pass_page", "Form"))
        self.lineEdit_oldPass.setPlaceholderText(_translate("change_pass_page", "Current Password"))
        self.label_newPass.setText(_translate("change_pass_page", "Mật khẩu mới"))
        self.label_oldPass.setText(_translate("change_pass_page", "Mật khẩu cũ"))
        self.changePass_Btn.setText(_translate("change_pass_page", "Change Password"))
        self.label_confirmPass.setText(_translate("change_pass_page", "Xác nhận mật khẩu"))
        self.lineEdit_newPass.setPlaceholderText(_translate("change_pass_page", "New password"))
        self.lineEdit_confirmPass.setPlaceholderText(_translate("change_pass_page", "Re-type new password"))
